project:
  type: website

website:
  title: "Machine Learning from Scratch"
  site-url: https://pda-sedano.github.io/ml-from-scratch
  navbar:
    left:
      - href: index.qmd
        text: Posts

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
